name: Linting

on:
  push:

jobs:
  linting-python:
    name: Lint Python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
    
      - name: Install dependencies
        if: always()
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pyright isort 

      - name: Run ruff
        if: always()
        shell: bash
        run: python -m ruff check prodigy_evaluate/ tests/ --fix

      - name: Run black
        if: always()
        shell: bash
        run: python -m black prodigy_evaluate/ tests/
    
      - name: Run isort
        if: always()
        shell: bash
        run: python -m isort prodigy_evaluate/ tests/